import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { DefaultResourceLoader, SettingsManager } from "@earendil-works/pi-coding-agent";
import { test } from "vitest";

const packageRoot = resolve("packages/pi-sync");
const builderUrl = pathToFileURL(join(packageRoot, "scripts/build-runtime.mjs")).href;

type BuildMetadata = {
	outputs?: Record<
		string,
		{
			entryPoint?: string;
			imports?: Array<{ external?: boolean; kind?: string; path: string }>;
			inputs?: Record<string, unknown>;
		}
	>;
};

type RuntimeBuilder = {
	buildRuntime(options?: {
		outputDirectory?: string;
		validateOutput?: (outputDirectory: string) => Promise<void>;
	}): Promise<BuildMetadata>;
	validateEagerGraph(metadata: BuildMetadata): {
		eagerInputs: Set<string>;
		eagerOutputs: Set<string>;
	};
};

async function loadBuilder(): Promise<RuntimeBuilder> {
	return (await import(`${builderUrl}?test=${crypto.randomUUID()}`)) as RuntimeBuilder;
}

test("generated runtime preserves every first-use import boundary", async () => {
	const builder = await loadBuilder();
	const root = await mkdtemp(join(packageRoot, ".pi-sync-build-test-"));
	try {
		const metadata = await builder.buildRuntime({ outputDirectory: join(root, "dist") });
		const { eagerInputs } = builder.validateEagerGraph(metadata);
		for (const lazyInput of [
			"src/setup-switch.ts",
			"src/sync-operations.ts",
			"src/manager-ui.ts",
			"src/manager-result-dispatcher.ts",
			"src/file-selection.ts",
			"src/remote-selection-ui.ts",
			"src/s3-backend.ts",
			"src/webdav-backend.ts",
			"src/git-backend.ts",
		]) {
			assert.equal(
				[...eagerInputs].some((input) => input.endsWith(`/${lazyInput}`)),
				false,
				`${lazyInput} became eager`,
			);
		}
	} finally {
		await rm(root, { force: true, recursive: true });
	}
});

test("generated runtime is mapped, external, self-contained, and loadable by Pi", async () => {
	const builder = await loadBuilder();
	const root = await mkdtemp(join(packageRoot, ".pi-sync-build-test-"));
	const agentDir = join(root, "agent");
	const output = join(root, "dist");
	const previousAgentDir = process.env.PI_CODING_AGENT_DIR;
	try {
		const metadata = await builder.buildRuntime({ outputDirectory: output });
		const files = await listFiles(output);
		assert.ok(files.includes("index.ts"));
		assert.ok(files.includes("index.ts.map"));
		assert.ok(files.some((path) => path.startsWith("chunks/") && path.endsWith(".ts")));
		for (const runtimePath of files.filter((path) => path.endsWith(".ts"))) {
			const source = await readFile(join(output, runtimePath), "utf8");
			assert.match(source, /^\/\/ @generated by scripts\/build-runtime\.mjs/u);
			assert.doesNotMatch(source, /["']\.\.?\/[^"']+\.js["']/u);
			assert.doesNotMatch(source, /["']\.\.?\/[^"']*src\//u);
			assert.ok(files.includes(`${runtimePath}.map`), `missing map for ${runtimePath}`);
		}
		assert.match(
			await readFile(join(output, "index.ts"), "utf8"),
			/["']\.\/chunks\/[^"']+\.ts["']/u,
		);
		for (const generated of Object.values(metadata.outputs ?? {})) {
			for (const input of Object.keys(generated.inputs ?? {})) {
				assert.equal(input.includes("node_modules/"), false, `bundled package input: ${input}`);
			}
		}

		await mkdir(agentDir, { recursive: true });
		process.env.PI_CODING_AGENT_DIR = agentDir;
		const loader = new DefaultResourceLoader({
			cwd: root,
			agentDir,
			settingsManager: SettingsManager.inMemory({}),
			additionalExtensionPaths: [join(output, "index.ts")],
		});
		await loader.reload();
		const loaded = loader.getExtensions();
		assert.deepEqual(loaded.errors, []);
		assert.equal(loaded.extensions.length, 1);
		assert.ok(loaded.extensions[0]?.commands.has("sync"));
	} finally {
		if (previousAgentDir === undefined) delete process.env.PI_CODING_AGENT_DIR;
		else process.env.PI_CODING_AGENT_DIR = previousAgentDir;
		await rm(root, { force: true, recursive: true });
	}
});

test("failed generated-output validation preserves the previous runtime", async () => {
	const builder = await loadBuilder();
	const root = await mkdtemp(join(packageRoot, ".pi-sync-build-test-"));
	try {
		const output = join(root, "dist");
		await mkdir(output, { recursive: true });
		await writeFile(join(output, "previous.ts"), "previous", "utf8");
		await assert.rejects(
			builder.buildRuntime({
				outputDirectory: output,
				validateOutput: async () => {
					throw new Error("injected validation failure");
				},
			}),
			/injected validation failure/u,
		);
		assert.deepEqual(await listFiles(output), ["previous.ts"]);
	} finally {
		await rm(root, { force: true, recursive: true });
	}
});

async function listFiles(directory: string, prefix = ""): Promise<string[]> {
	const { readdir } = await import("node:fs/promises");
	const files: string[] = [];
	for (const entry of await readdir(join(directory, prefix), { withFileTypes: true })) {
		const relativePath = join(prefix, entry.name);
		if (entry.isDirectory()) files.push(...(await listFiles(directory, relativePath)));
		else if (entry.isFile()) files.push(relativePath.replaceAll("\\", "/"));
	}
	return files.sort();
}
